---
title: "social_media_presence"
author: "Lisa Rothmann"
date: "26/05/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#library

```{r}
library(tidyverse)
library(gsheet)
library(ggthemes)
```

# data
```{r}
scl.sm <- gsheet2tbl("https://docs.google.com/spreadsheets/d/1-bCNbueVD-9tLurdJAHW-SkV3slUs3ash4tXenhY-Zc/edit?usp=sharing")

scl.sm<-scl.sm %>% 
  mutate(asdate = case_when(
                            Date == "18 August 2020" ~ as.Date("08/18/2020", format='%m/%d/%Y'),
                            Date == "10 September 2020" ~ as.Date("09/10/2020", format='%m/%d/%Y'),
                            Date == "5 November 2020" ~ as.Date("11/5/2020", format='%m/%d/%Y'),
                            Date == "24 February 2021" ~ as.Date("02/24/2021", format='%m/%d/%Y'),
                            Date == "25 May 2021" ~ as.Date("05/25/2021", format='%m/%d/%Y'),
                            Date == "24 August 2021" ~ as.Date("08/24/2021", format='%m/%d/%Y'),
                            Date == "25 February 2022" ~ as.Date("02/25/2022", format='%m/%d/%Y')))
```

```{r}
scl.sm %>% 
ggplot +
  geom_point(aes(asdate, Followers, color = Platform), size = 5)+
  geom_line(aes(asdate, Followers, color = Platform, group = Platform), size = 2)+
  theme_clean(base_size =14)
  ggsave("logo/vis/sm_trends.jpeg", units = "cm", width = 21, height = 7)
  
```

